version: '3.7'

services:
  db:
    container_name: "db"
    build: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demopassword2022 # developer local environment
      MYSQL_DATABASE: classicmodel
  graphql:
    container_name: "graphql"
    build: graphql
    volumes:
      - "./graphql:/src"
      - "/src/node_modules"
  restapi:
    container_name: "restapi"
    build: restapi
    volumes:
      - "./restapi:/src"
      - "/src/node_modules"
  proxy:
    container_name: "proxy"
    build: proxy
    restart: always
    volumes:
      - "./proxy:/src"
      - "/src/node_modules"
    environment:
      PROXY_USER: graphql # developer local environment
      PROXY_PASSWORD: demopassword2022 # developer local environment
      API_GATEWAY: gateway:3000 # developer local environment
      IP_USA: 207.97.227.239
      IP_CANADA: 103.151.126.50
      IP_PANAMA: 201.226.52.23
      IP_ACTIVE: REMOTE
      IP_DOCKER: INVALID
    ports:
      - 80:3000
  gateway:
    container_name: "gateway"
    build: gateway
    restart: always
    volumes:
      - "./gateway:/src"
      - "/src/node_modules"
    environment:
      API_GRAPHQL_HOST: graphql:4000
      API_REST_HOST: restapi:3000